
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubmetheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: config-vol
          configMap: 
            name: prometheus-config
      containers:
      - name: prometheus
        image: prom/prometheus:v2.33.4
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-vol
          mountPath: /etc/prometheus/prometheus.yml
          subPath: scrapeconfig.yml