apiVersion: v1
kind: Service
metadata:
  name: kubmetheus-svc
  labels:
    app: kubmetheus
spec:
  selector:
    app: kubmetheus
  type: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000