apiVersion: v1
kind: Service
metadata:
  name: kubmetheus-svc
  labels:
    app: kubmetheus
spec:
  selector:
    app: kubmetheus
  type: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---      
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: kubmetheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
